vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        tricks_thumbnail:
            uri_prefix: /tricks/thumbnail
            upload_destination: '%kernel.project_dir%/public/tricks/thumbnail'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        tricks_gallery:
            uri_prefix: /tricks/gallery
            upload_destination: '%kernel.project_dir%/public/tricks/gallery'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false
